name = "centralwebdesk"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-03-25"

[[d1_databases]]
binding = "DB"
database_name = "centralwebdesk"
database_id = "c49899b6-9cd2-453e-b2c7-b963c6a834bb"
